on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "pom.xml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "pom.xml"

name: Code Coverage

permissions:
  pull-requests: write

jobs:
  generic_handler:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUBTOKEN }}
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'
          check-latest: true

      - name: Build with Maven - other
        run: mvn -B package -DskipAntRunForJenkins --file pom.xml -pl '!frontend'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cordys-dev/cordys-crm